Repository nicholasyager/dbt-loom, pull requests merged in 2023-11, with the labels that each got.

#21 feat: add support for GCS
  README.md
  dbt_loom/__init__.py
  dbt_loom/clients/gcs.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#22 Feature: Add Support for S3-based object storage as a manifest source
  README.md
  dbt_loom/__init__.py
  dbt_loom/clients/gcs.py
  dbt_loom/clients/s3.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#24 docs: Update status of S3 support in the README
  README.md
Labels: documentation

#26 Fix: Correct date parsing for `deprecation_date`
  dbt_loom/__init__.py
  test_projects/revenue/models/marts/__models.yml
  test_projects/revenue/models/marts/orders_v1.sql
  test_projects/revenue/models/marts/orders_v2.sql
Labels: bug
