Repository nicholasyager/dbt-loom, pull requests merged in 2024-06, with the labels that each got.

#60 Feature: Support cross-project Group evaluation
  dbt_loom/__init__.py
  dbt_loom/manifests.py
  test_projects/revenue/dbt_project.yml
  test_projects/revenue/models/groups.yml
  test_projects/revenue/models/marts/__models.yml
  test_projects/revenue/models/marts/accounts.sql
  test_projects/revenue/models/staging/stg_accounts.sql
  test_projects/revenue/seeds/__seeds.yml
  test_projects/revenue/seeds/seed_accounts.csv
  tests/test_dbt_core_execution.py
Labels: bug, enhancement

#66 Fix: Support dbt-core 1.8.x
  pyproject.toml
Labels: bug

#69 docs: Add a documentation section for gzipped files
  README.md
Labels: documentation
