Repository nicholasyager/dbt-loom, pull requests merged in 2025-04, with the labels that each got.

#120 Show a message when config file not exits
  dbt_loom/__init__.py
Labels: enhancement

#116 Support DBT Manifests from Snowflake Stage
  README.md
  dbt_loom/clients/snowflake_stage.py
  dbt_loom/config.py
  dbt_loom/manifests.py
Labels: enhancement

#122 Fix: Minor enhancement and bug fixes associated with snowflake stages as a data source.
  README.md
  dbt_loom/clients/snowflake_stage.py
  docs/getting-started.md
  poetry.lock
  pyproject.toml
Labels: bug

#124 fix: Correct the header type for Snowflake Stage docs
  docs/getting-started.md
Labels: documentation
